### ISSUE TITLE
Memory limitation 

### ISSUE THREAD

**Issue by olegdunkan** [eaburns/flac#7]
Hello, let say we have not enough memory to decode all flac data, your implementation returns    
all data (located in memory) in one time. Maybe it is better to return some kind of frame reader which allows us to get decoded frame by frame? It can be implemented via go bufio package. 
Thanks for decoder.

**Comment by eaburns** [comment]
I think you can make a Decoder and call Next. At least that's the intent.

**Comment by olegdunkan** [comment]
Ohh, yes of course, sorry for question. I didn't pay attention enough. Thanks for support!

**Comment by eaburns** [comment]
No problem. Glad you've found the package useful.
